name: Cargo tests

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Run cargo test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Show rustc and cargo versions
        run: |
          rustc -Vv
          cargo -Vv

      - name: Run tests
        run: cargo test --all --locked
